# Generated by Django 6.0.2 on 2026-02-18 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='productModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=255)),
                ('price_per_unit', models.IntegerField()),
                ('avilable_quantity', models.IntegerField()),
                ('unit_type', models.CharField(max_length=20)),
                ('quality_grade', models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('Organic', 'Organic'), ('Premium', 'Premium')], max_length=20)),
                ('Harvest_date', models.DateField()),
                ('decription', models.CharField(max_length=150)),
                ('org_norg', models.CharField(choices=[('Organic', 'Organic'), ('Non-Organic', 'Non-Organic')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('delivery_option', models.CharField(max_length=50)),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
