# Generated by Django 6.0.2 on 2026-02-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmerApp', '0002_alter_productmodel_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='avilable_quantity',
            new_name='available_quantity',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='Harvest_date',
            new_name='harvest_date',
        ),
    ]
