# Generated by Django 6.0.2 on 2026-02-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmerApp', '0003_rename_avilable_quantity_productmodel_available_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='decription',
            new_name='description',
        ),
    ]
