# Generated by Django 6.0.2 on 2026-02-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmerApp', '0006_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='org_norg',
        ),
    ]
