# Generated by Django 6.0.2 on 2026-03-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmerApp', '0008_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='quality_grade',
            field=models.CharField(choices=[('A', '5'), ('B', '4'), ('c', '3'), ('d', '2'), ('e', '1')], max_length=20),
        ),
    ]
