# Generated by Django 6.0.2 on 2026-03-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmerApp', '0009_alter_productmodel_quality_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='quality_grade',
            field=models.CharField(choices=[('A', '5'), ('B', '4'), ('C', '3'), ('D', '2'), ('E', '1')], max_length=20),
        ),
    ]
