# Generated by Django 6.0.2 on 2026-03-04 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmerApp', '0010_alter_productmodel_quality_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='product_img',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.ImageField(upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='FarmerApp.productmodel')),
            ],
        ),
    ]
