# Generated by Django 6.0.2 on 2026-03-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmerApp', '0011_remove_productmodel_product_img_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
